cmd = 'python ./exp_sgpr_ips.py -l "{uid}"'

[[exp]]
cmd = 'XLA_FLAGS="--xla_tensor_size_threshold={limit}" {cmd}  -c {compile} -s {seed} -d {dataset} -m {numips} -mi {maxiters}'
uid = './{rootdir}/{name}/{dataset}/{limit}/sgpr_tips{numips}_i{maxiters}/{seed}'

name = "ips"
limit = "1GB"
compile = "xla"
rootdir = "logs_sgpr"
seed = [111]
dataset = ["3droad"]
numips = [7000, 10000]
maxiters = 500

[flags]
restart = false
num_proc = 2
gpu_indices = ["2", "3"]
#num_proc = 1 
#gpu_indices = ["0"]
