cmd = 'XLA_FLAGS="--xla_tensor_size_threshold={limit} --xla_tensor_split_size={limit} --xla_disable_hlo_passes=tensor-splitter" python ./exp_sgpr_ips.py -l "{uid}"'

[[exp]]

cmd = '{cmd}  -c {compile} -s {seed} -d {dataset} -m {numips} -mi {maxiters}'
uid = './{rootdir}/{dataset}/{limit}/sgpr_tips{numips}_i{maxiters}/{seed}'

name = "ips"
limit = "1GB"
compile = "xla"
rootdir = "logs/exp_sgpr_ips"
seed = [111]
dataset = ["houseelectric"]
numips = [1000]
maxiters = 1000

[flags]
restart = false
num_proc = 1
gpu_indices = ["3"]
#num_proc = 1 
#gpu_indices = ["0"]
