#cmd = 'TF_CPP_MIN_LOG_LEVEL=0 python ./bench.py --logdir "{uid}"'
cmd = 'python ./exp_sgpr.py --logdir "{uid}"'

[[exp]]
cmd = 'XLA_FLAGS="--xla_try_split_tensor_size={limit}" {cmd} -s {seed} -d {dataset} -m {numips} -ni {maxiters} -np {numphases}'
uid = './{rootdir}/{name}/{dataset}/{limit}/sgpr_ips{numips}_np{numphases}_ni{maxiters}/{seed}'

name = "ips"
limit = "1GB"
rootdir = "logs_sgpr"
# dataset = ["keggundirected"]
seed = [111, 222]
dataset = ["kin40k"]
# numips = [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]
numips = [500, 1000, 2000]
numphases = 4
maxiters = 1000  # per phase

[flags]
restart = false
num_proc = 4
gpu_indices = ["0", "1", "2", "3"]
#num_proc = 1 
#gpu_indices = ["0"]
