#cmd = 'TF_CPP_MIN_LOG_LEVEL=0 python ./bench.py --logdir "{uid}"'
cmd = 'python ./bench.py --logdir "{uid}"'

[[exp]]
cmd = 'XLA_FLAGS="--xla_try_split_tensor_size={limit}" {cmd} -f {float} -r {repeat} -w {warm} {kind} -k {kernel} -d {dataset} -m {num_ips}'
uid = './{rootdir}/{name}/{dataset}-{limit}-{kernel}-{num_ips}'

name = "sgpr-inducing-points"
# limit = ["1GB", "5GB"]
limit = "2GB"
rootdir = "logs"
kind = "sgpr"
kernel = ["matern32"]
dataset = ["houseelectric"]
num_ips = [500, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]
repeat = 1
warm = 1
float = "fp64"

[flags]
restart = false
num_proc = 1
gpu_indices = ["2"]
#num_proc = 2
#gpu_indices = ["0", "1"]
