cmd = 'python ./bench.py --logdir "{uid}"'

[[exp]]
cmd = 'XLA_FLAGS="--xla_try_split_tensor_size={limit}" {cmd} -f {float} -r {repeat} -w {warm} {kind} -k {kernel} -a "({num}, {dim})" -b "({num}, {dim})" -v "({num}, 1)"'
uid = './{rootdir}/{name}/{kernel}-{limit}-{float}-{num}-{dim}'

# limit = ["1GB", "5GB", "15GB", "25GB"]
name = "memvar"
limit = ["1GB", "5GB"]
rootdir = "logs"
kind = "kvp"
kernel = ["se"]
# num = [1000, 10_000, 100_000, 500_000, 1_000_000, 5_000_000, 10_000_000]
num = [10_000, 100_000, 500_000]
# num = [1_000_000]
dim = [10]
repeat = 10
warm = 2
float = "fp64"

[flags]
restart = false
num_proc = 4
gpu_indices = ["0", "1", "2", "3"]
