cmd = 'python ./bench.py --warmup 10 --repeat 100'

[[exp]]
cmd = '{cmd} {kind} -i "({num}, {dim})"'
uid = './{rootdir}/{kind}/{float}/shape_{num}_{dim}'

rootdir = "logs"
kind = "outerprod-with-itself"
num = [100, 1000, 10_000, 100_000, 1_000_000]
dim = [100, 1000]
float = ["fp64", "fp32"]

[[exp]]
cmd = '{cmd} {kind} -a "({num}, {dim})" -b "({num}, {dim})" -v "({num}, 1)"'
uid = './{rootdir}/{kind}/{float}/{kernel}_{num}_{dim}'

rootdir = "logs"
kind = "kernel"
kernel = ["se", "linear"]
num = [100, 1000, 10_000, 100_000, 1_000_000]
dim = [100, 1000]
float = ["fp64", "fp32"]

[flags]
restart = false
num_proc = 4
gpu_indices = ["0", "1", "2", "4"]