cmd = 'python ./exp_knn.py -l "{uid}"'

##################################################
# Random L2 TF and JAX
[[exp]]
cmd = 'XLA_FLAGS="--xla_try_split_tensor_size={limit}" {cmd} -b {backend} -s {seed} -d random_n{datasize}_d{datadim}_m{querysize} -r {repeat} -w {warmup} -c {distance}'
uid = './{rootdir}/{backend}_{limit}/{distance}_random_n{datasize}_d{datadim}_m{querysize}/{seed}'

warmup = 1
repeat = 1
limit = "100MB"
rootdir = "logs_knn"
seed = 111
backend = ["jax", "tf"]
distance = "L2"
datasize = [10_000, 1_000_000, 10_000_000]
datadim = [3, 10, 100]
querysize = [10000]

# Random L2 TF-pure and JAX-pure
[[exp]]
cmd = 'XLA_FLAGS="--xla_try_split_tensor_size={limit}" {cmd} -b {backend} -s {seed} -d random_n{datasize}_d{datadim}_m{querysize} -r {repeat} -w {warmup} -c {distance}'
uid = './{rootdir}/{backend}/{distance}_random_n{datasize}_d{datadim}_m{querysize}/{seed}'

warmup = 1
repeat = 1
limit = "100GB"
rootdir = "logs_knn"
seed = 111
backend = ["jax-pure", "tf-pure"]
distance = "L2"
datasize = [10_000, 1_000_000, 10_000_000]
datadim = [3, 10, 100]
querysize = [10000]

# Random L2 Keops
[[exp]]
cmd = '{cmd} -b {backend} -s {seed} -d random_n{datasize}_d{datadim}_m{querysize} -r {repeat} -w {warmup} -c {distance}'
uid = './{rootdir}/{backend}/{distance}_random_n{datasize}_d{datadim}_m{querysize}/{seed}'

warmup = 1
repeat = 1
rootdir = "logs_knn"
seed = 111
backend = "keops"
distance = "L2"
datasize = [10_000, 1_000_000, 10_000_000]
datadim = [3, 10, 100]
querysize = [10000]

##################################################
# Random (L1 and cosine) TF and JAX
[[exp]]
cmd = 'XLA_FLAGS="--xla_try_split_tensor_size={limit}" {cmd} -b {backend} -s {seed} -d random_n{datasize}_d{datadim}_m{querysize} -r {repeat} -w {warmup} -c {distance}'
uid = './{rootdir}/{backend}_{limit}/{distance}_random_n{datasize}_d{datadim}_m{querysize}/{seed}'

warmup = 1
repeat = 1
limit = "100MB"
rootdir = "logs_knn"
seed = 111
backend = ["tf", "jax"]
distance = ["L1", "cosine"]
datasize = [1_000_000]
datadim = [10, 100]
querysize = [10000]

# Random (L1 and cosine) TF-pure and JAX-pure
[[exp]]
cmd = 'XLA_FLAGS="--xla_try_split_tensor_size={limit}" {cmd} -b {backend} -s {seed} -d random_n{datasize}_d{datadim}_m{querysize} -r {repeat} -w {warmup} -c {distance}'
uid = './{rootdir}/{backend}/{distance}_{dataset}_m{querysize}/{seed}'

warmup = 1
repeat = 1
limit = "100GB"
rootdir = "logs_knn"
seed = 111
backend = ["tf-pure", "jax-pure"]
distance = ["L1", "cosine"]
datasize = [1_000_000]
datadim = [10, 100]
querysize = [10000]

# Random (L1 and cosine) Keops
[[exp]]
cmd = '{cmd} -b {backend} -s {seed} -d random_n{datasize}_d{datadim}_m{querysize} -r {repeat} -w {warmup} -c {distance}'
uid = './{rootdir}/{backend}/{distance}_random_n{datasize}_d{datadim}_m{querysize}/{seed}'

warmup = 1
repeat = 1
rootdir = "logs_knn"
seed = 111
backend = "keops"
distance = ["L1", "cosine"]
datasize = [1_000_000]
datadim = [10, 100]
querysize = [10000]


##################################################
# Cosine glove TF and JAX
[[exp]]
cmd = 'XLA_FLAGS="--xla_try_split_tensor_size={limit}" {cmd} -b {backend} -s {seed} -d {dataset} -r {repeat} -w {warmup} -c {distance}'
uid = './{rootdir}/{backend}_{limit}/{distance}_{dataset}/{seed}'

warmup = 1
repeat = 1
limit = "100MB"
rootdir = "logs_knn"
seed = 111
dataset = ["glove50", "glove100", "glove200"]
backend = ["jax", "tf"]
distance = "cosine"
querysize = [10000]

# Cosine glove TF-pure and JAX-pure
[[exp]]
cmd = 'XLA_FLAGS="--xla_try_split_tensor_size={limit}" {cmd} -b {backend} -s {seed} -d {dataset} -r {repeat} -w {warmup} -c {distance}'
uid = './{rootdir}/{backend}/{distance}_{dataset}/{seed}'

warmup = 1
repeat = 1
limit = "100GB"
rootdir = "logs_knn"
seed = 111
dataset = ["glove50", "glove100", "glove200"]
backend = ["jax-pure", "tf-pure"]
distance = "cosine"
querysize = [10000]

# Cosine glove Keops
[[exp]]
cmd = '{cmd} -b {backend} -s {seed} -d {dataset} -r {repeat} -w {warmup} -c {distance}'
uid = './{rootdir}/{backend}/{distance}_{dataset}/{seed}'

warmup = 1
repeat = 1
rootdir = "logs_knn"
seed = 111
dataset = ["glove50", "glove100", "glove200"]
backend = "keops"
distance = "cosine"
querysize = [10000]

################################
# L2/L1 mnist/fashion TF and JAX
[[exp]]
cmd = 'XLA_FLAGS="--xla_try_split_tensor_size={limit}" {cmd} -b {backend} -s {seed} -d {dataset}_m{querysize} -r {repeat} -w {warmup} -c {distance}'
uid = './{rootdir}/{backend}_{limit}/{distance}_{dataset}_m{querysize}/{seed}'

warmup = 1
repeat = 1
limit = "100MB"
rootdir = "logs_knn"
seed = 111
dataset = ["mnist", "fashion"]
backend = ["jax", "tf"]
distance = ["L2", "L1"]
querysize = [10000]


# L2/L1 mnist/fashion TF-pure and JAX-pure
[[exp]]
cmd = 'XLA_FLAGS="--xla_try_split_tensor_size={limit}" {cmd} -b {backend} -s {seed} -d {dataset}_m{querysize} -r {repeat} -w {warmup} -c {distance}'
uid = './{rootdir}/{backend}/{distance}_{dataset}_m{querysize}/{seed}'

warmup = 1
repeat = 1
limit = "100GB"
rootdir = "logs_knn"
seed = 111
dataset = ["mnist", "fashion"]
backend = ["jax-pure", "tf-pure"]
distance = ["L2", "L1"]
querysize = [10000]

# L2/L1 mnist/fashion Keops
[[exp]]
cmd = '{cmd} -b {backend} -s {seed} -d {dataset}_m{querysize} -r {repeat} -w {warmup} -c {distance}'
uid = './{rootdir}/{backend}/{distance}_{dataset}_m{querysize}/{seed}'

warmup = 1
repeat = 1
rootdir = "logs_knn"
seed = 111
dataset = ["mnist", "fashion"]
backend = "keops"
distance = ["L2", "L1"]
querysize = [10000]


[flags]
restart = false
num_proc = 4
gpu_indices = ["0", "1", "2", "3"]