cmd = 'python ./exp_knn.py -l "{uid}"'

# L2/L1 mnist/fashion TF and JAX
[[exp]]
cmd = 'XLA_FLAGS="--xla_try_split_tensor_size={limit}" {cmd} -b {backend} -s {seed} -d {dataset}_m{querysize} -r {repeat} -w {warmup} -c {distance}'
uid = './{rootdir}/{backend}_{limit}/{distance}_{dataset}_m{querysize}/{seed}'

warmup = 1
repeat = 1
limit = "100MB"
rootdir = "logs_knn"
seed = 111
dataset = ["mnist", "fashion"]
backend = ["jax", "tf"]
distance = ["L2", "L1"]
querysize = [10000]

# L2/L1 mnist/fashion Keops
[[exp]]
cmd = '{cmd} -b {backend} -s {seed} -d {dataset}_m{querysize} -r {repeat} -w {warmup} -c {distance}'
uid = './{rootdir}/{backend}/{distance}_{dataset}_m{querysize}/{seed}'

warmup = 1
repeat = 1
rootdir = "logs_knn"
seed = 111
dataset = ["mnist", "fashion"]
backend = "keops"
distance = ["L2", "L1"]
querysize = [10000]


[flags]
restart = false
num_proc = 2
gpu_indices = ["1", "2"]