cmd = 'python ./exp_sgpr_iter_speed.py -l "{uid}"'

##################################################
# No gradient
[[exp]]
cmd = 'XLA_FLAGS="--xla_try_split_tensor_size={limit}" {cmd} --no-grad-ips -c {compile} -s {seed} -d {dataset} -m {numips} -r {repeat} -w {warmup}'
uid = './{rootdir}/{compile}_{limit}_nograd/{dataset}_ips{numips}/{seed}'

warmup = 1
repeat = 1
limit = "1GB"
rootdir = "logs_sgpr_speed"
seed = 111
compile = "xla"
dataset = ["houseelectric", "3droad"]
numips = [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]

##################################################
# Include gradient evaluation

[[exp]]
cmd = 'XLA_FLAGS="--xla_try_split_tensor_size={limit}" {cmd} --grad-ips -c {compile} -s {seed} -d {dataset} -m {numips} -r {repeat} -w {warmup}'
uid = './{rootdir}/{compile}_{limit}_grad/{dataset}_ips{numips}/{seed}'

warmup = 1
repeat = 1
limit = "1GB"
rootdir = "logs_sgpr_speed"
seed = 111
compile = "xla"
dataset = ["houseelectric", "3droad"]
numips = [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]


[flags]
restart = false
num_proc = 4
gpu_indices = ["0", "1", "2", "3"]